import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className,"w-full min-h-screen ")}>
        {children}
        {/* <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Incidunt explicabo accusantium quae, adipisci aut blanditiis eligendi ipsam optio asperiores sed, quis nulla amet voluptates ratione quos culpa vel laboriosam impedit.</p> */}
      </body>
    </html>
  );
}
